### ISSUE TITLE
Not satisfied with the name

### ISSUE THREAD

**Issue by kkoomen** [mozilla-mobile/guardian-vpn-ios#255]
The name chosen for this project is "Private Network VPN" which means "Private Network Virtual Private Network" which is redundant. Could this be renamed to "Private Network" or just "VPN"?

**Comment by chrismore** [comment]
Thank you for your feedback about the name of the beta product. 

We are excited to share that we will be launching the official product, the Mozilla VPN (no more name redundancy), in the next few weeks. Feel free to learn more about it here: 

https://blog.mozilla.org/futurereleases/2020/06/18/introducing-firefox-private-network-vpns-official-product-the-mozilla-vpn/
