### ISSUE TITLE
Try Mozilla VPN button does not take to the proper site

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/guardian-vpn-ios#279]
Seen using latest build from develop bran on iPhone 8 (iOS 13.7 and 13.5) simulator. 
Also reproducible on latest stage build from TF on real device

**Steps**
After log in using a stage account, on main view click on the Try Mozilla VPN button. On the new screen open click on the Try Mozilla VPN button at the bottom

**Actual**
Nothing happens when clicking on that button
![Captura de pantalla 2020-10-28 a las 13 13 19](https://user-images.githubusercontent.com/1897507/97434724-bb2e8200-191f-11eb-97a0-c53b36ae839e.png)

**Expected**
Upon clicking on the button the correct site is open allowing user to try the VPN

**Comment by rlr** [comment]
This is the In-App purchases build. That button is supposed to trigger the purchase but something isn't set up right. Do you have experience to help set it up? Thanks!

**Comment by madalincm** [comment]
@rlr I reproduced this issue on a real device (Iphone SE, ios 13.1.2) using the build from test flight. Do we need to follow some special setup when setting the build on the device?

**Comment by rlr** [comment]
I think we need to finish setting up the subscription in app store connect. I'm trying to sort this out with releng.

![image](https://user-images.githubusercontent.com/36629/97435680-244dcf80-18f7-11eb-8614-21fd6c82b437.png)

**Comment by rlr** [comment]
@madalincm @isabelrios OK, the product ID was wrong in the backend. I was able to get it to work now although it wasn't super smooth. I had to sign off and back on after paying to get the VPN to work. Let me know how it goes for you. Thanks!

**Comment by rlr** [comment]
I think the issue in my case was the transaction took so long that I clicked away before it was done. Be patient once confirming the purchase. We probably need to add a processing spinner screen there.

**Comment by isabelrios** [comment]
thanks @rlr for fixing it so fast! :) for me it does not work yet but I see an error when clicking on that button, which is different from the previous behaviour. It may be because I'm using a simulator and not a real device. @madalincm was able to click on that button and complete the process on a real device although he found a few issues in the way that he will comment so that they are investiaged in case of real bugs.

**Comment by madalincm** [comment]
as @isabelrios mentioned I was able to complete the subscription. I started filling some issues where I will describe the other bugs I'm encountering.

**Comment by rlr** [comment]
fixed by the server side change + #285

I'll get a new build out to test flight
