### ISSUE TITLE
Remove a device warning displayed in the app after the user creates a subscription from the website

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/guardian-vpn-ios#280]
#### Affected versions:
- iOS VPN App 1.0.8 installed from test flight

#### Affected Platforms:
- iphone SE, iOS 13.1.2

#### Preconditions:
- Existent FxA account that hasn't a vpn subscription set up

#### Steps to reproduce:
1. Open the vpn app on the ios device and log in with the fxa account that does not have a subscription set up
2. Open the vpn website and create a subscription for the account used at step 1
3. Go back to the vpn app on the iOS device settings - My devices menu

 #### Expected result:
- The user can turn on the vpn app on the ios device and in the my device menu the connected device is displayed.

#### Actual result:
- The user is not able to turn on the vpn and in the my device menu the Remove a device warning is displayed 
![removeDevice](https://user-images.githubusercontent.com/15685441/97437750-9987c780-192c-11eb-8552-ef27ce944a01.JPEG)

#### Notes
If the user signs out and relogs he is able to turn on the vpn.

**Comment by rlr** [comment]
fixed by #285

I'll get a new build out to test flight

**Comment by madalincm** [comment]
Verified as fixed on iphone SE, iOS 13.1.2, Vpn app version 1.0.8 (936)

The issue is no longer reproducing. After creating the account the vpn can now be started.
