### ISSUE TITLE
Display issues in the Payment screen

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/guardian-vpn-ios#282]
#### Affected versions:
- iOS VPN App 1.0.8 installed from test flight

#### Affected Platforms:
- iphone SE, iOS 13.1.2

#### Preconditions:
- Existent FxA account that hasn't a vpn subscription set up

#### Steps to reproduce:
1. Open the vpn app on the ios device and log in with the fxa account that does not have a subscription set up
2. Tap on the **Try Mozilla VPN** blue banner
3. Observe the page

 #### Expected result:
- There are no display issues

#### Actual result:
- The Mozilla vpn logo from the top of the page is cut
- There is no padding on the right side for the **280+ servers in 30+ countries** text
- There is no padding under the **Restore purchase** link at the bottom of the page

![image](https://user-images.githubusercontent.com/15685441/97440471-2c763100-1930-11eb-87c5-a2097758ac77.png)

**Comment by rlr** [comment]
fixed by #285

I'll get a new build out to test flight

**Comment by madalincm** [comment]
Verified as fixed on iphone SE, iOS 13.1.2, Vpn app version 1.0.8 (936)
![282Fix](https://user-images.githubusercontent.com/15685441/97869073-7dfc3280-1d19-11eb-9538-34eb55a3d6c6.jpg)
